if(WIN32)
  if(MSVC)
    set(prefix "" CACHE INTERNAL "")
    set(suffix ".lib" CACHE INTERNAL "")
  endif()
  if(MINGW)
    set(prefix "lib" CACHE INTERNAL "")
    set(suffix ".dll.a" CACHE INTERNAL "")
  endif()
elseif(APPLE)
  set(prefix "lib" CACHE INTERNAL "")
  set(suffix ".a" CACHE INTERNAL "")
elseif(UNIX)
  set(prefix "lib" CACHE INTERNAL "")
  set(suffix ".a" CACHE INTERNAL "")
endif()
