#include "QvisVCRWidget.h"
#include "ui_QvisVCRWidget.h"

#include "../icons/animate/animationreversestep.xpm"

#include "../icons/animate/animationreverseplayoff.xpm"
#include "../icons/animate/animationreverseplayon.xpm"

#include "../icons/animate/animationstopoff.xpm"
#include "../icons/animate/animationstopon.xpm"

#include "../icons/animate/animationplayoff.xpm"
#include "../icons/animate/animationplayon.xpm"

#include "../icons/animate/animationforwardstep.xpm"

QvisVCRWidget::QvisVCRWidget(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::QvisVCRWidget)
{
    ui->setupUi(this);

    // Because the widget is compiled as a QDesigner plugin and the project the
    // icon relative path via the qrc for each will be different as such get the
    // icons via the file's realtive path which does not change for either.
    // Note: ui_QvisVCRWidget.h could be edited but it is auto generated by QDesigner.
    QIcon icon0;
    icon0.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
    icon0.addPixmap(QPixmap(animationreversestep_xpm), QIcon::Selected, QIcon::On);
    ui->ReverseSingleStep->setIcon(icon0);

    QIcon icon1;
    icon1.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
    icon1.addPixmap(QPixmap(animationreverseplayoff_xpm), QIcon::Selected, QIcon::Off);
    icon1.addPixmap(QPixmap(animationreverseplayon_xpm), QIcon::Selected, QIcon::On);
    ui->Reverse->setIcon(icon1);

    QIcon icon2;
    icon2.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
    icon2.addPixmap(QPixmap(animationstopoff_xpm), QIcon::Selected, QIcon::Off);
    icon2.addPixmap(QPixmap(animationstopon_xpm), QIcon::Selected, QIcon::On);
    ui->Stop->setIcon(icon2);

    QIcon icon3;
    icon3.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
    icon3.addPixmap(QPixmap(animationplayoff_xpm), QIcon::Selected, QIcon::Off);
    icon3.addPixmap(QPixmap(animationplayon_xpm), QIcon::Selected, QIcon::On);
    ui->Play->setIcon(icon3);

    QIcon icon4;
    icon4.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
    icon4.addPixmap(QPixmap(animationforwardstep_xpm), QIcon::Selected, QIcon::On);
    ui->ForwardSingleStep->setIcon(icon4);
}

QvisVCRWidget::~QvisVCRWidget()
{
    delete ui;
}

void QvisVCRWidget::ReverseSingleStepClicked()
{
    const QSignalBlocker blocker0(ui->Reverse);
    const QSignalBlocker blocker1(ui->Stop);
    const QSignalBlocker blocker2(ui->Play);

    ui->Reverse->setChecked(false);
    ui->Stop->setChecked(true);
    ui->Play->setChecked(false);

    emit reverseSingleStep();
}

void QvisVCRWidget::ReverseClicked()
{
    const QSignalBlocker blocker0(ui->Reverse);
    const QSignalBlocker blocker1(ui->Stop);
    const QSignalBlocker blocker2(ui->Play);

    ui->Reverse->setChecked(true);
    ui->Stop->setChecked(false);
    ui->Play->setChecked(false);

    emit reverse();
}

void QvisVCRWidget::StopClicked()
{
    const QSignalBlocker blocker0(ui->Reverse);
    const QSignalBlocker blocker1(ui->Stop);
    const QSignalBlocker blocker2(ui->Play);

    ui->Reverse->setChecked(false);
    ui->Stop->setChecked(true);
    ui->Play->setChecked(false);

    emit stop();
}

void QvisVCRWidget::PlayClicked()
{
    const QSignalBlocker blocker0(ui->Reverse);
    const QSignalBlocker blocker1(ui->Stop);
    const QSignalBlocker blocker2(ui->Play);

    ui->Reverse->setChecked(false);
    ui->Stop->setChecked(false);
    ui->Play->setChecked(true);

    emit play();
}

void QvisVCRWidget::ForwardSingleStepClicked()
{
    const QSignalBlocker blocker0(ui->Reverse);
    const QSignalBlocker blocker1(ui->Stop);
    const QSignalBlocker blocker2(ui->Play);

    ui->Reverse->setChecked(false);
    ui->Stop->setChecked(true);
    ui->Play->setChecked(false);

    emit forwardSingleStep();
}
