name: osx-build

on: push

jobs:
  osx-build-gui:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Qt
      run: brew install qt

    - name: Configure
      run: mkdir build && ls /usr/local/Cellar/qt/5.14.1

#    - name: Run CMake
#      working-directory: build
#      run: cmake .. -G "Xcode" 

