name: windows-build

on: [push,pull_request]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure
      shell: powershell
      run: .\.WinSetup\winSetup.ps1 ; mkdir build

    - name: Run_Cmake
      working-directory: build
      shell: powershell
      run: cmake ..

    - name: Build
      shell: powershell
      run: cmake --build 
