name: windows-build

on: [push,pull_request]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Download_OpenCL_Headers
      shell: powershell
      run: git clone --branch v2020.03.13 https://github.com/KhronosGroup/OpenCL-Headers/

    - name: Download_OpenCL_Libraries
      shell: powershell
      run: git clone --branch v2020.03.13 https://github.com/KhronosGroup/OpenCL-ICD-Loader/

    - name: Install_OpenCL
      shell: powershell
      run: .\.WinSetup\winSetup.ps1

    - name: Install Qt
      uses: ouuan/install-qt-action@ouuan
      with:
        version: 5.13.1
        target: desktop
        host: windows
        arch: win64_msvc2017_64
        install-deps: true

    - name: Print out Qt Dir
      shell: powershell
      run: echo $env:Qt5_Dir ; cd .. ; ls ; cd Qt ; ls ; cd 5.13.1 ; ls

    - name: Run_Cmake
      working-directory: build
      shell: cmd
      run: cmake -DOpenCL_LIBRARY:PATH="..\OpenCL\lib\Release" -DOpenCL_INCLUDE_DIR:PATH="..\OpenCL\OpenCL-ICD-Loader\inc" -DCMAKE_PREFIX_PATH:PATH="$..\Qt\5.13.1\msvc2017_64" ..

    - name: Build
      shell: cmd
      run: cmake --build 
