name: windows-build

on: [push,pull_request]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure
      shell: powershell
      run: .\.WinSetup\winSetup.ps1 ; mkdir build ; cd build ; cmake ..\ -G "Visual Studio 16 2019"

    - name: Build
      shell: powershell
      run: cmake --build 
