name: windows-build

on: [push,pull_request]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure
      shell: powershell
      run: .\.WinSetup\winSetup.ps1 ; mkdir build
    
    - name: Download_OpenCL_Headers
      shell: powershell
      run: git clone --branch v2020.03.13 https://github.com/KhronosGroup/OpenCL-Headers/

    - name: Download_OpenCL_Libraries
      shell: powershell
      run: git clone --branch v2020.03.13 https://github.com/KhronosGroup/OpenCL-ICD-Loader/

    - name: Install_OpenCL
      shell: powershell
      run: .\.WinSetup\winSetupPt2.ps1

    - name: Run_Cmake
      working-directory: build
      shell: powershell
      run: cmake -DOpenCL_LIBRARY=..\OpenCL\lib\Release -DOpenCL_INCLUDE_DIR=..\OpenCL\OpenCL-ICD-Loader\inc ..

    - name: Build
      shell: powershell
      run: cmake --build 
