/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaToC */

#ifndef _Included_JavaToC
#define _Included_JavaToC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaToC
 * Method:    allocateMemory
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_JavaToC_allocateMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaToC
 * Method:    writeToMemory
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_JavaToC_writeToMemory
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
